### ISSUE TITLE
IPv4 addresses serialization glitch (?)

### ISSUE THREAD

**Issue by jurov** [haskoin/haskoin#107]
To get correct serialized representation of address for bitcoin protocol, I had to reverse (change endianness) serialized IPv4 address, despite its encoded ByteString output is already in correct endianness. Meanwhile, to add to the confusion, prefix and port number must be left unchanged. This is seen from following function to convert from standard SockAddr:

```
-- make NetworkAddress from SockAddr
fromSockAddr :: SockAddr -> NetworkAddress
fromSockAddr a = case a of
    --convert to IPv6 mapped IPV4, big endian
    --https://en.bitcoin.it/wiki/Protocol_specification#Network_address
    SockAddrInet pn ha -> let 
        ips = BSL.reverse $ encode ha --WHY this must be reversed?
        Just prefix = hexToBS "0000ffff"
        lower = decode $ BSL.concat [toLazyBS prefix,ips] :: Word64
        ws = (0,lower) :: (Word64,Word64)
        in NetworkAddress 1 ws (fromIntegral pn)
    SockAddrInet6 pn fi ha sid -> let
        ws = decode $ encode ha :: (Word64,Word64)
        in NetworkAddress 1 ws (fromIntegral pn)
```

Maybe I'm making a mistake due to being a haskell newbie, but IMO the format (Word64,Word64) for NetworkAddress input isn't very well chosen and may cause headaches/bugs in future. I'd suggest to use (Word8, Word8....) instead.

**Comment by jprupp** [comment]
Pull request #108 fixes these issues by using SockAddr from inside NetworkAddress, and taking care not to change endianness when (de)serializing SockAddrInet.

**Comment by sha49** [comment]
ACK
