### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by Fuuzetsu** [haskoin/haskoin#109]
http://hydra.nixos.org/build/14260477/log/raw

**Comment by jprupp** [comment]
Hey Fuuzetsu,

I did not see this yesterday.  I'll get to the bottom of it.

Cheers!

**Comment by Fuuzetsu** [comment]
I neglected to mention this but that's for i686. It seems more or less fine for 64-bit:

http://hydra.nixos.org/job/nixpkgs/staging/haskellPackages_ghc783.haskoin.x86_64-linux
http://hydra.nixos.org/job/nixpkgs/staging/haskellPackages_ghc783.haskoin.i686-linux

**Comment by jprupp** [comment]
Fixed by #110
