### ISSUE TITLE
scripts need to be decoded at runtime

### ISSUE THREAD

**Issue by OttoAllmendinger** [haskoin/haskoin#28]
a funny thing happend parsing the test suite from the BitcoinQt client

```
> runTest
Canonical Valid Script Test Cases:
  sig: [0]  pubKey: [IF 0xfd ELSE 1 ENDIF] : [Failed]
can't parse key: "IF 0xfd ELSE 1 ENDIF" error: byte decode error: demandInput: not enough bytes
  sig: [0]  pubKey: [IF 0xfe ELSE 1 ENDIF] : [Failed]
can't parse key: "IF 0xfe ELSE 1 ENDIF" error: byte decode error: Get: Invalid public key encoding
```

It turns out that the byte sequences `0xfd` (`OP_PUBKEYHASH`) and `0xfd` (`OP_PUBKEY`) inside an unexecuted `IF` branch are valid and ignored. But when read in an if-branch that is executed, we need to push the subsequent N bytes on the stack. 

This prevents us from deserializing the byte sequence statically, meaning we can't use this instance

``` haskell
instance Binary Script where
    get = 
        Script <$> getScriptOps
      where
        getScriptOps = do
            empty <- isEmpty
            if empty 
                then return [] 
                else liftM2 (:) get getScriptOps

    put (Script ops) = forM_ ops put
```

**Comment by m0dev76** [comment]
Good catch! It seems that we can not tokenize the script before it is being evaluated. I will remove this instance and create a function for the encoding part. We will have to de-serialize the script on-the-fly while evaluating it.

**Comment by m0dev76** [comment]
There is something we might want to consider: OP_PUBKEYHASH and OP_PUBKEY are internal opcodes used in bitcoind. They seem to be invalid if used in actual scripts (according to https://en.bitcoin.it/wiki/Script). So if these are the only opcodes that fail to tokenize, we could consider ignoring them in haskoin as we should never see them.

**Comment by OttoAllmendinger** [comment]
True, it seems they are only used as a helper in templating tx scripts and don't indicate that a `Hash160` or `pubKey` follow. They are basically the same as `OP_INVALIDOPCODE`, and `OP_RESERVED`: in an executed if-branch they mark the tx as invalid, in an unexecuted branch they are ignored. 

I fixed it in my branch: https://github.com/OttoAllmendinger/haskoin/commit/46be34868d8ccd7196ef16d3fe053714e97eca8f

So static de-serialization might still be possible

**Comment by OttoAllmendinger** [comment]
not an issue after all, seems to work fine now
