### ISSUE TITLE
BuildMonad should go in Transaction or go away

### ISSUE THREAD

**Issue by jprupp** [haskoin/haskoin#38]
The Build monad is currently used for transaction validation, therefore it should go in Transaction, and not in Util.

**Comment by jprupp** [comment]
@plaprade thinks that the BuildMonad just makes things complicated, and it should go away. I agree.

**Comment by m0dev76** [comment]
Removed the BuildMonad in this pull request:
https://github.com/haskoin/haskoin/pull/42
